const W=1200,H=630,S=16;
type Asset={image:HTMLImageElement;name:string;uploaded:boolean}; type Gradient="solid"|"horizontal"|"vertical"|"radial"; type Color={kind:"color";primary:string;secondary:string;gradient:Gradient}; type Background=Asset|Color;
const id=<T extends HTMLElement>(name:string)=>document.getElementById(name) as T;
const canvas=id<HTMLCanvasElement>("preview-canvas"), wrap=id<HTMLDivElement>("canvas-wrap"), statusElement=id<HTMLParagraphElement>("status"), download=id<HTMLButtonElement>("download-button"), primary=id<HTMLInputElement>("primary-color"), secondary=id<HTMLInputElement>("secondary-color");
let background:Background|null=null, screenshot:Asset|null=null, loading=true, hasResult=false, statusMessage="";
const setStatus=(message:string)=>{statusMessage=message;statusElement.textContent=loading?"Reading image…":message};
const setResult=(ready:boolean)=>{hasResult=ready;wrap.classList.toggle("ready",ready);download.disabled=!ready};
const isColor=(value:Background):value is Color=>"kind" in value;
const shadow=()=>id<HTMLInputElement>("shadow-toggle").checked;
const blurBackground=()=>id<HTMLInputElement>("background-blur-toggle").checked;
const syncBlurOption=()=>{const option=id<HTMLElement>("background-blur-option"),enabled=!!background&&!isColor(background)&&background.uploaded;option.hidden=!enabled;if(!enabled)id<HTMLInputElement>("background-blur-toggle").checked=false};
const radius=()=>Number(document.querySelector<HTMLInputElement>("input[name='corner-radius']:checked")?.value??32);
const padding=()=>Number(document.querySelector<HTMLInputElement>("input[name='screenshot-padding']:checked")?.value??25);
const gradient=()=>document.querySelector<HTMLInputElement>("input[name='gradient-style']:checked")?.value as Gradient;
function imageFrom(src:string,name:string,uploaded=false,objectUrl=false):Promise<Asset>{return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{if(objectUrl)URL.revokeObjectURL(src);resolve({image,name,uploaded})};image.onerror=()=>{if(objectUrl)URL.revokeObjectURL(src);reject(new Error("read"))};image.src=src})}
function blurLayer(ctx:CanvasRenderingContext2D,image:HTMLImageElement,x:number,y:number,width:number,height:number){const layer=document.createElement("canvas");layer.width=W;layer.height=H;const layerContext=layer.getContext("2d");if(!layerContext)return;layerContext.drawImage(image,x,y,width,height);const pixels=layerContext.getImageData(0,0,W,H),source=pixels.data,horizontal=new Uint8ClampedArray(source.length),radius=20,diameter=radius*2+1,clamp=(value:number,max:number)=>Math.max(0,Math.min(max,value));for(let row=0;row<H;row++){let red=0,green=0,blue=0;for(let offset=-radius;offset<=radius;offset++){const index=(row*W+clamp(offset,W-1))*4;red+=source[index];green+=source[index+1];blue+=source[index+2]}for(let column=0;column<W;column++){const index=(row*W+column)*4;horizontal[index]=red/diameter;horizontal[index+1]=green/diameter;horizontal[index+2]=blue/diameter;horizontal[index+3]=source[index+3];const remove=(row*W+clamp(column-radius,W-1))*4,add=(row*W+clamp(column+radius+1,W-1))*4;red+=source[add]-source[remove];green+=source[add+1]-source[remove+1];blue+=source[add+2]-source[remove+2]}}for(let column=0;column<W;column++){let red=0,green=0,blue=0;for(let offset=-radius;offset<=radius;offset++){const index=(clamp(offset,H-1)*W+column)*4;red+=horizontal[index];green+=horizontal[index+1];blue+=horizontal[index+2]}for(let row=0;row<H;row++){const index=(row*W+column)*4;source[index]=red/diameter*.9;source[index+1]=green/diameter*.9;source[index+2]=blue/diameter*.9;source[index+3]=horizontal[index+3];const remove=(clamp(row-radius,H-1)*W+column)*4,add=(clamp(row+radius+1,H-1)*W+column)*4;red+=horizontal[add]-horizontal[remove];green+=horizontal[add+1]-horizontal[remove+1];blue+=horizontal[add+2]-horizontal[remove+2]}}ctx.putImageData(pixels,0,0)}
function drawBackground(ctx:CanvasRenderingContext2D,value:Background){if(!isColor(value)){const blurred=value.uploaded&&blurBackground(),zoom=blurred?1.1:1,scale=Math.max(W/value.image.naturalWidth,H/value.image.naturalHeight)*zoom,width=value.image.naturalWidth*scale,height=value.image.naturalHeight*scale,x=(W-width)/2,y=(H-height)/2;if(blurred)blurLayer(ctx,value.image,x,y,width,height);else ctx.drawImage(value.image,x,y,width,height);return}if(value.gradient==="solid")ctx.fillStyle=value.primary;else{const g=value.gradient==="radial"?ctx.createRadialGradient(W/2,H/2,0,W/2,H/2,Math.max(W,H)/1.25):ctx.createLinearGradient(0,0,value.gradient==="horizontal"?W:0,value.gradient==="vertical"?H:0);g.addColorStop(0,value.primary);g.addColorStop(1,value.secondary);ctx.fillStyle=g}ctx.fillRect(0,0,W,H)}
function preview(value:Background){const ctx=canvas.getContext("2d");if(!ctx)return;canvas.width=W;canvas.height=H;ctx.clearRect(0,0,W,H);drawBackground(ctx,value);wrap.classList.add("has-background");setResult(false)}
function render(){if(!background||!screenshot)return;const ctx=canvas.getContext("2d");if(!ctx){setStatus("Your browser cannot generate this image.");return}canvas.width=W;canvas.height=H;ctx.clearRect(0,0,W,H);drawBackground(ctx,background);const inset=padding(),scale=Math.min(1,(W-2*(inset+S))/screenshot.image.naturalWidth,(H-2*(inset+S))/screenshot.image.naturalHeight),width=screenshot.image.naturalWidth*scale,height=screenshot.image.naturalHeight*scale,x=(W-width)/2,y=(H-height)/2,r=Math.min(radius(),width/2,height/2);if(shadow()){ctx.save();ctx.shadowColor="rgba(12, 19, 37, 0.36)";ctx.shadowBlur=26;ctx.fillStyle="#182336";ctx.beginPath();ctx.roundRect(x,y,width,height,r);ctx.fill();ctx.restore()}ctx.save();ctx.beginPath();ctx.roundRect(x,y,width,height,r);ctx.clip();ctx.drawImage(screenshot.image,x,y,width,height);ctx.restore();wrap.classList.add("has-background");setResult(true);setStatus("Your 1200 × 630 visual is ready to download.")}
function mode(value:string){document.querySelectorAll<HTMLButtonElement>("[data-background-mode]").forEach(button=>button.classList.toggle("active",button.dataset.backgroundMode===value));document.querySelectorAll<HTMLElement>("[data-background-panel]").forEach(panel=>panel.hidden=panel.dataset.backgroundPanel!==value)}
async function preset(button:HTMLButtonElement){const src=button.dataset.presetSrc,name=button.dataset.presetName;if(!src||!name)return;mode("presets");loading=true;setStatus("");try{background=await imageFrom(src,name);syncBlurOption();document.querySelectorAll<HTMLButtonElement>("[data-preset-src]").forEach(item=>{const chosen=item===button;item.classList.toggle("selected",chosen);item.setAttribute("aria-pressed",String(chosen))});if(screenshot)render();else{preview(background);setStatus("Background selected. Add the screenshot.")}}catch{setStatus("This background image could not be read.")}finally{loading=false;setStatus(statusMessage)}}
function color(){const value:Color={kind:"color",primary:primary.value,secondary:secondary.value,gradient:gradient()};id<HTMLOutputElement>("primary-color-value").value=primary.value.toUpperCase();id<HTMLOutputElement>("secondary-color-value").value=secondary.value.toUpperCase();id<HTMLElement>("primary-color-label").textContent=value.gradient==="solid"?"Color":"First color";id<HTMLElement>("secondary-color-control").hidden=value.gradient==="solid";background=value;syncBlurOption();mode("color");if(screenshot)render();else{preview(value);setStatus("Color background selected. Add the screenshot.")}}
async function upload(file:File|undefined,kind:"background"|"screenshot"){if(!file)return;if(!file.type.startsWith("image/")){loading=false;setStatus("Choose a PNG, JPEG, or WebP image file.");return}loading=true;setStatus("");try{const asset=await imageFrom(URL.createObjectURL(file),file.name,kind==="background",true);if(kind==="background"){background=asset;syncBlurOption();id<HTMLElement>("background-file-name").textContent=asset.name;mode("upload");if(screenshot)render();else{preview(asset);setStatus("Background loaded. Add the screenshot.")}}else{screenshot=asset;syncBlurOption();id<HTMLElement>("screenshot-file-name").textContent=asset.name;if(background)render();else{setResult(false);setStatus("Screenshot loaded. Choose or upload a background.")}}}catch{setStatus("This file could not be read. Try another image.")}finally{loading=false;setStatus(statusMessage)}}
document.querySelectorAll<HTMLButtonElement>("[data-preset-src]").forEach(button=>button.addEventListener("click",()=>void preset(button)));
document.querySelectorAll<HTMLButtonElement>("[data-background-mode]").forEach(button=>button.addEventListener("click",()=>{const value=button.dataset.backgroundMode??"presets";if(value==="presets"){const selected=document.querySelector<HTMLButtonElement>(".preset-card.selected")??document.querySelector<HTMLButtonElement>("[data-preset-src]");if(selected)void preset(selected)}else if(value==="color")color();else mode(value)}));
function fileDrop(card:HTMLElement,kind:"background"|"screenshot"){let dragDepth=0;const hasFiles=(event:DragEvent)=>{const transfer=event.dataTransfer;return !!transfer&&(transfer.files.length>0||Array.from(transfer.items).some(item=>item.kind==="file"))};card.addEventListener("dragenter",event=>{if(!hasFiles(event))return;event.preventDefault();dragDepth++;card.classList.add("is-dragging")});card.addEventListener("dragover",event=>{if(!hasFiles(event))return;event.preventDefault();if(event.dataTransfer)event.dataTransfer.dropEffect="copy"});card.addEventListener("dragleave",event=>{if(!hasFiles(event))return;dragDepth--;if(dragDepth<=0){dragDepth=0;card.classList.remove("is-dragging")}});card.addEventListener("drop",event=>{if(!hasFiles(event))return;event.preventDefault();dragDepth=0;card.classList.remove("is-dragging");void upload(event.dataTransfer?.files[0],kind)})}
const backgroundUpload=id<HTMLInputElement>("background-upload"),screenshotUpload=id<HTMLInputElement>("screenshot-upload");backgroundUpload.addEventListener("change",()=>void upload(backgroundUpload.files?.[0],"background"));screenshotUpload.addEventListener("change",()=>void upload(screenshotUpload.files?.[0],"screenshot"));fileDrop(backgroundUpload.closest<HTMLElement>(".upload-card")!,"background");fileDrop(screenshotUpload.closest<HTMLElement>(".upload-card")!,"screenshot");document.querySelectorAll<HTMLInputElement>("input[name='gradient-style']").forEach(input=>input.addEventListener("change",color));primary.addEventListener("input",color);secondary.addEventListener("input",color);id<HTMLInputElement>("shadow-toggle").addEventListener("change",render);id<HTMLInputElement>("background-blur-toggle").addEventListener("change",()=>{if(!background)return;if(screenshot)render();else preview(background)});document.querySelectorAll<HTMLInputElement>("input[name='corner-radius']").forEach(input=>input.addEventListener("change",render));document.querySelectorAll<HTMLInputElement>("input[name='screenshot-padding']").forEach(input=>input.addEventListener("change",render));download.addEventListener("click",()=>{if(!hasResult)return;const link=document.createElement("a");link.download="composed-screenshot-1200x630.png";link.href=canvas.toDataURL("image/png");link.click()});const initial=document.querySelector<HTMLButtonElement>("[data-preset-src]");if(initial)void preset(initial);
