const W=1200,H=630,M=25,S=16;
type Asset={image:HTMLImageElement;name:string}; type Gradient="solid"|"horizontal"|"vertical"|"radial"; type Color={kind:"color";primary:string;secondary:string;gradient:Gradient}; type Background=Asset|Color;
const id=<T extends HTMLElement>(name:string)=>document.getElementById(name) as T;
const canvas=id<HTMLCanvasElement>("preview-canvas"), wrap=id<HTMLDivElement>("canvas-wrap"), statusElement=id<HTMLParagraphElement>("status"), download=id<HTMLButtonElement>("download-button"), primary=id<HTMLInputElement>("primary-color"), secondary=id<HTMLInputElement>("secondary-color");
let background:Background|null=null, screenshot:Asset|null=null, loading=true, hasResult=false, statusMessage="";
const setStatus=(message:string)=>{statusMessage=message;statusElement.textContent=loading?"Reading image…":message};
const setResult=(ready:boolean)=>{hasResult=ready;wrap.classList.toggle("ready",ready);download.disabled=!ready};
const isColor=(value:Background):value is Color=>"kind" in value;
const shadow=()=>id<HTMLInputElement>("shadow-toggle").checked;
const radius=()=>Number(document.querySelector<HTMLInputElement>("input[name='corner-radius']:checked")?.value??32);
const gradient=()=>document.querySelector<HTMLInputElement>("input[name='gradient-style']:checked")?.value as Gradient;
function imageFrom(src:string,name:string,objectUrl=false):Promise<Asset>{return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{if(objectUrl)URL.revokeObjectURL(src);resolve({image,name})};image.onerror=()=>{if(objectUrl)URL.revokeObjectURL(src);reject(new Error("read"))};image.src=src})}
function drawBackground(ctx:CanvasRenderingContext2D,value:Background){if(!isColor(value)){const scale=Math.max(W/value.image.naturalWidth,H/value.image.naturalHeight),width=value.image.naturalWidth*scale,height=value.image.naturalHeight*scale;ctx.drawImage(value.image,(W-width)/2,(H-height)/2,width,height);return}if(value.gradient==="solid")ctx.fillStyle=value.primary;else{const g=value.gradient==="radial"?ctx.createRadialGradient(W/2,H/2,0,W/2,H/2,Math.max(W,H)/1.25):ctx.createLinearGradient(0,0,value.gradient==="horizontal"?W:0,value.gradient==="vertical"?H:0);g.addColorStop(0,value.primary);g.addColorStop(1,value.secondary);ctx.fillStyle=g}ctx.fillRect(0,0,W,H)}
function preview(value:Background){const ctx=canvas.getContext("2d");if(!ctx)return;canvas.width=W;canvas.height=H;ctx.clearRect(0,0,W,H);drawBackground(ctx,value);wrap.classList.add("has-background");setResult(false)}
function render(){if(!background||!screenshot)return;const ctx=canvas.getContext("2d");if(!ctx){setStatus("Your browser cannot generate this image.");return}canvas.width=W;canvas.height=H;ctx.clearRect(0,0,W,H);drawBackground(ctx,background);const scale=Math.min(1,(W-2*(M+S))/screenshot.image.naturalWidth,(H-2*(M+S))/screenshot.image.naturalHeight),width=screenshot.image.naturalWidth*scale,height=screenshot.image.naturalHeight*scale,x=(W-width)/2,y=(H-height)/2,r=Math.min(radius(),width/2,height/2);if(shadow()){ctx.save();ctx.shadowColor="rgba(12, 19, 37, 0.36)";ctx.shadowBlur=26;ctx.fillStyle="#182336";ctx.beginPath();ctx.roundRect(x,y,width,height,r);ctx.fill();ctx.restore()}ctx.save();ctx.beginPath();ctx.roundRect(x,y,width,height,r);ctx.clip();ctx.drawImage(screenshot.image,x,y,width,height);ctx.restore();wrap.classList.add("has-background");setResult(true);setStatus("Your 1200 × 630 visual is ready to download.")}
function mode(value:string){document.querySelectorAll<HTMLButtonElement>("[data-background-mode]").forEach(button=>button.classList.toggle("active",button.dataset.backgroundMode===value));document.querySelectorAll<HTMLElement>("[data-background-panel]").forEach(panel=>panel.hidden=panel.dataset.backgroundPanel!==value)}
async function preset(button:HTMLButtonElement){const src=button.dataset.presetSrc,name=button.dataset.presetName;if(!src||!name)return;mode("presets");loading=true;setStatus("");try{background=await imageFrom(src,name);document.querySelectorAll<HTMLButtonElement>("[data-preset-src]").forEach(item=>{const chosen=item===button;item.classList.toggle("selected",chosen);item.setAttribute("aria-pressed",String(chosen))});if(screenshot)render();else{preview(background);setStatus("Background selected. Add the screenshot.")}}catch{setStatus("This background image could not be read.")}finally{loading=false;setStatus(statusMessage)}}
function color(){const value:Color={kind:"color",primary:primary.value,secondary:secondary.value,gradient:gradient()};id<HTMLOutputElement>("primary-color-value").value=primary.value.toUpperCase();id<HTMLOutputElement>("secondary-color-value").value=secondary.value.toUpperCase();id<HTMLElement>("primary-color-label").textContent=value.gradient==="solid"?"Color":"First color";id<HTMLElement>("secondary-color-control").hidden=value.gradient==="solid";background=value;mode("color");if(screenshot)render();else{preview(value);setStatus("Color background selected. Add the screenshot.")}}
async function upload(input:HTMLInputElement,kind:"background"|"screenshot"){const file=input.files?.[0];if(!file)return;if(!file.type.startsWith("image/")){loading=false;setStatus("Choose a PNG, JPEG, or WebP image file.");input.value="";return}loading=true;setStatus("");try{const asset=await imageFrom(URL.createObjectURL(file),file.name,true);if(kind==="background"){background=asset;id<HTMLElement>("background-file-name").textContent=asset.name;mode("upload");if(screenshot)render();else{preview(asset);setStatus("Background loaded. Add the screenshot.")}}else{screenshot=asset;id<HTMLElement>("screenshot-file-name").textContent=asset.name;if(background)render();else{setResult(false);setStatus("Screenshot loaded. Choose or upload a background.")}}}catch{setStatus("This file could not be read. Try another image.")}finally{loading=false;setStatus(statusMessage)}}
document.querySelectorAll<HTMLButtonElement>("[data-preset-src]").forEach(button=>button.addEventListener("click",()=>void preset(button)));
document.querySelectorAll<HTMLButtonElement>("[data-background-mode]").forEach(button=>button.addEventListener("click",()=>{const value=button.dataset.backgroundMode??"presets";if(value==="presets"){const selected=document.querySelector<HTMLButtonElement>(".preset-card.selected")??document.querySelector<HTMLButtonElement>("[data-preset-src]");if(selected)void preset(selected)}else if(value==="color")color();else mode(value)}));
id<HTMLInputElement>("background-upload").addEventListener("change",event=>void upload(event.currentTarget as HTMLInputElement,"background"));id<HTMLInputElement>("screenshot-upload").addEventListener("change",event=>void upload(event.currentTarget as HTMLInputElement,"screenshot"));document.querySelectorAll<HTMLInputElement>("input[name='gradient-style']").forEach(input=>input.addEventListener("change",color));primary.addEventListener("input",color);secondary.addEventListener("input",color);id<HTMLInputElement>("shadow-toggle").addEventListener("change",render);document.querySelectorAll<HTMLInputElement>("input[name='corner-radius']").forEach(input=>input.addEventListener("change",render));download.addEventListener("click",()=>{if(!hasResult)return;const link=document.createElement("a");link.download="composed-screenshot-1200x630.png";link.href=canvas.toDataURL("image/png");link.click()});const initial=document.querySelector<HTMLButtonElement>("[data-preset-src]");if(initial)void preset(initial);
